#!/usr/bin/env bash

echo "

Setting up Node js for app
----------------------
"
echo "
----------------------
Cloning node sources
----------------------
"
sudo apt-get install curl

curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -"



echo "
----------------------
Installing Nodejs
----------------------
"
sudo apt-get install nodejs

echo "
----------------------
Node version
----------------------
"
node -v

echo "
----------------------
Installing pm2 server
----------------------
"
sudo npm i -g pm2

echo "
----------------------
Success
----------------------
"